backend:
  name: git-gateway
  branch: main

media_folder: "."       # Pfad relativ zum Repo-Root → speichert Uploads im Root-Verzeichnis  
public_folder: "/"      # URL-Pfad im gebauten Site → /<dateiname>

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - file: "index.html"
        label: "Startseite"
        name: "startseite"
        fields:                            # ← hier ergänzen
          - label: "Öffnungszeiten"
            name: "opening_hours"
            widget: "list"
            fields:
              - { label: "Tage", name: "days", widget: "string" }
              - { label: "Uhrzeiten", name: "hours", widget: "string" }