backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/media"  
public_folder: "/media"      

collections:
  - name: "site_data"
    label: "Site Data"
    files:
      - file: "src/data/site_data.json"
        name: "site_data"
        format: "json"
        label: "Website-Daten"
        fields:
          - label: "Öffnungszeiten"
            name: "opening_hours"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Tage", name: "days", widget: "string" }
              - { label: "Uhrzeiten", name: "hours", widget: "string" }